### ISSUE TITLE
Example of text-generation from model 

### ISSUE THREAD

**Issue by dhowe** [EleutherAI/tokengrams#21]
> Our code also allows you to turn your suffix array index into *an efficient n-gram language model, which can be used to generate text* or compute the perplexity of a given text.

Looking for a simple demo of this, thanks

**Comment by luciaquirke** [comment]
Hey, thanks for the question! Here's a text generation example: https://colab.research.google.com/drive/1CEHoIjLboGl8YPbIqnWJlPYMm1wVOrrj?usp=sharing

Let me know if you have any issues!
