### ISSUE TITLE
Error on pip install

### ISSUE THREAD

**Issue by dhowe** [EleutherAI/tokengrams#6]
`$ pip install tokengrams`

ERROR: Could not find a version that satisfies the requirement tokengrams (from versions: none)
ERROR: No matching distribution found for tokengrams

I'm tried on OS X 11.7.9 intel and Ubuntu 18.04.6

**Comment by luciaquirke** [comment]
Hello and sorry for the slow response! This was caused by a problem with our manual release process, I've fixed and automated it so installs should work reliably now, let me know if you still have the issue.
